language: node_js
node_js:
  - "8"
  - "node"

env:
  global:
    - BUILD_TIMEOUT=20000

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm ci || npm install

script:
  - npm run lint
